base_url: "http://192.168.1.93:2727/v1"
model: 'Qwen2.5-7B-AWQ'
password: 'password'  # так делать плохо
rag_settings:
  mode: 'standard'
  answer_temperature: 0.7
  router_enable: True
  router_temperature: 0.7
  db_enable: True
  chunk_count: 10
  reranker_enable: True
  reranker_temperature: 0.5
  chain_of_thoughts: False
  chat_id: 0